package com.forgemagic.mobs;

public final class MobBaseValues {
 private MobBaseValues(){}
 public static long centavos(String type){return switch(type){
  case "ZOMBIE","SKELETON","SPIDER","CAVE_SPIDER","HUSK","STRAY","DROWNED","SLIME","MAGMA_CUBE","SILVERFISH","ENDERMITE","PHANTOM","HOGLIN","ZOGLIN"->10;
  case "CREEPER","PILLAGER","VINDICATOR","EVOKER","VEX","RAVAGER","GUARDIAN","SHULKER","GHAST","PIGLIN","PIGLIN_BRUTE","ZOMBIFIED_PIGLIN","BREEZE","BOGGED"->25;
  case "ENDERMAN","WITCH","WITHER_SKELETON","BLAZE","WOLF","POLAR_BEAR","GOAT","BEE"->50;
  case "ELDER_GUARDIAN","WARDEN","WITHER","ENDER_DRAGON"->1000;
  case "ALLAY","ARMADILLO","AXOLOTL","BAT","CAMEL","CAT","CHICKEN","COD","COW","DOLPHIN","DONKEY","FOX","FROG","HORSE","IRON_GOLEM","LLAMA","MOOSHROOM","MULE","OCELOT","PANDA","PARROT","PIG","PUFFERFISH","RABBIT","SALMON","SHEEP","SNIFFER","SQUID","STRIDER","TADPOLE","TROPICAL_FISH","TURTLE","VILLAGER","WANDERING_TRADER","ZOMBIE_HORSE","SKELETON_HORSE"->5;
  default->0;};}
}
